apiVersion: v1
kind: Secret
metadata:
  name: demodebezium-secrets
  namespace: debezium
type: Opaque
stringData:
  # Event Hub connection string
  eh-connection-string: <your-azure-eventhub-connection-string>

  # Azure SQL Database credentials
  sqlserver-username: sqladmin
  sqlserver-password: cfacilbr@demo